[functions]
  node_bundler = "esbuild"
  included_files = ["cars.json", "users.json", "rentItem.json"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
